### PR TITLE
`.juliabundleignore` should apply to top-level files, too

### LINKED ISSUE #100: .juliabundleignore doesn't work?
I tried to to launch a batch job with a large folder in my bundle (but tried to use .juliabundleignore file to ignore it). It doesn't seem to work. 

Image

**To Reproduce**

Put a large file > 2GB at the top level and tried the following patterns: 
*.avi
assets/ (having moved the file there)

**Environment**

Using extension 0.7.11 locally on my mac. 

- **Is this happening locally, in a JuliaHub IDE, or in a JuliaHub batch job?**
- **JuliaHub.jl version:** 6.9.1
- **Relevant JuliaHub instance:** `internal.juliahub.com`
- **Julia version:** 1.11.4
- **Operating system:** Mac

Need this to work with a series of files too (*.csv etc etc)

Image

Image

### PR DESCRIPTION
**Pull request by mbauman**
The appbundle's `.juliabundleignore` was previously not picking up for files in the same directory.  This is a simple change to effectively make the loop a do-while.

Fix #100.

### CODE REVIEW

File: src/PackageBundler/utils.jl [hunk 1]
```diff
@@ -95,7 +95,6 @@ function get_bundleignore(file, top)
     end
     return patterns, top
 end
```
Comment (mortenpi) [inline src/PackageBundler/utils.jl:97]:
```suggestion
end

```

**Review by pfitzseb — APPROVED** [review]
